println "Example for checking permissions"

aecu
    .validateAccessRights()
    .forPaths("/content/we-retail/us/en/men", "/content/we-retail/de", "/content/we-retail/fr")
    .forGroups("content-authors")
    .canRead()
    .canModify()
    .canCreate()
    .canDelete()
    .canReplicate()
    .cannotReadAcl()
    .cannotWriteAcl()
    .canReadPage()
    .canDeletePage()
    .forPaths("/content/we-retail/us/en/products")
    .canCreatePage("/conf/we-retail/settings/wcm/templates/content-page")
    .cannotCreatePage("/conf/we-retail/settings/wcm/templates/nonexisting-page")
    .forGroups("contributor")
    .canRead()
    .cannotModify()
    .cannotCreate()
    .cannotDelete()
    .cannotReplicate()
    .cannotReadAcl()
    .cannotWriteAcl()
    .canReadPage()
    .cannotDeletePage()
    .forGroups("administrators")
    .canRead()
    .canModify()
    .canCreate()
    .canDelete()
    .canReadAcl()
    .canWriteAcl()
    .canReadPage()
    .canDeletePage()
    .validate()
    
    aecu
    .validateAccessRights()
    .forPaths("/content/we-retail/us/en/men")
    .forGroups("content-authors")
    .canReplicatePage(ReplicationActionType.ACTIVATE)
//    .simulate()
    .validate();